services:
  # nginx:
  #   image: nginx:latest
  #   container_name: nginx
  #   ports:
  #     - "80:80"
  #   volumes:
  #     - ./nginx/nginx.conf:/etc/nginx/nginx.conf
  #   depends_on:
  #     - ghost
  #     #- apache-answer
  #     - mysql

  ghost:
    image: ghost:latest
    container_name: ghost
    environment:
      url: http://localhost
      database__client: postgres
      database__connection__host: db-ghost
      database__connection__user: ghost_user
      database__connection__password: ghost_password
      database__connection__database: ghost_db
      database__connection__port: 5432
    depends_on:
      - db-ghost
    ports:
      - "2368:2368"

  # apache-answer:
  #   build:
  #     context: .
  #     dockerfile: ./Dockerfile
  #   container_name: apache-answer
  #   environment:
  #     DB_TYPE: mysql
  #     DB_HOST: mysql
  #     DB_USERNAME: ${DB_USER_APACHE_ANSWER}
  #     DB_PASSWORD: ${DB_PASSWORD_APACHE_ANSWER}
  #     LANGUAGE: de_DE
  #     SITE_NAME: Community
  #     DB_NAME: ${DB_NAME_APACHE_ANSWER}
  #     ADMIN_NAME: admin
  #     ADMIN_EMAIL: ${ADMIN_EMAIL}
  #     CONTACT_EMAIL: ${ADMIN_EMAIL}
  #     ADMIN_PASSWORD: ${ANSWER_ADMIN_PASSWORD}
  #     SITE_URL: http://localhost:9080/community
  #     AUTO_INSTALL: true
  #   depends_on:
  #     mysql:
  #       condition: service_healthy
  #   ports:
  #     - "9080:9080"
  #   volumes:
  #     - ./configs/config.yaml:/data/conf/config.yaml

  # mysql:
  #   image: mysql:latest
  #   container_name: mysql
  #   restart: always
  #   environment:
  #     MYSQL_ROOT_PASSWORD: root_password
  #     MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
  #   healthcheck:
  #     test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
  #     interval: 2s
  #     timeout: 1s
  #     retries: 3
  #   volumes:
  #     - mysql-data:/var/lib/mysql
  #     - ./mysql/init-scripts:/docker-entrypoint-initdb.d
  #   ports:
  #     - "3306:3306"

  db-ghost:
    image: postgres
    environment:
      - POSTGRES_DB=ghost_db
      - POSTGRES_USER=ghost_user
      - POSTGRES_PASSWORD=ghost_password
    ports:
      - 5432
    volumes:
      - ghost-volume:/var/lib/postgresql/data

  db-answer:
    image: postgres
    environment:
      - POSTGRES_DB=answer_db
      - POSTGRES_USER=answer_user
      - POSTGRES_PASSWORD=answer_password
    ports:
      - 5432
    volumes:
      - answer-volume:/var/lib/postgresql/data

volumes:
  #answer-data:
  #mysql-data:
  ghost-volume:
  answer-volume:
